//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SecurityRes.rc
//
#define IDS_TITLE1                      1
#define IDS_SUBTITLE1                   2
#define IDS_TITLE2                      3
#define IDS_SUBTITLE2                   4
#define IDS_CAPTION                     5
#define IDS_SUBTITLE3                   5
#define IDS_SUBTITLE4                   6
#define IDS_TITLE3                      7
#define IDS_TITLE5                      8
#define IDS_SUBTITLE5                   9
#define IDS_TITLE0                      12
#define IDS_SUBTITLE0                   13
#define IDS_TITLE4                      14
#define IDS_TITLE6                      15
#define IDS_SUBTITLE6                   16
#define IDS_TITLE7                      17
#define IDS_SUBTITLE7                   18
#define IDS_TITLE8                      19
#define IDS_TITLE10                     19
#define IDS_SUBTITLE8                   20
#define IDS_SUBTITLE10                  20
#define IDS_TITLE9                      21
#define IDS_SUBTITLE9                   22
#define IDB_BANNER                      102
#define IDB_WATERMARK                   103
#define IDD_INTERIOR3                   106
#define IDD_COMMON_NAME                 106
#define IDD_INTRO                       107
#define IDI_ICON1                       107
#define IDD_INTERIOR1                   108
#define IDD_KEY_STRENGTH                108
#define IDD_INTERIOR2                   109
#define IDB_BITMAP4                     109
#define IDD_ORG_DLG                     109
#define IDD_END                         110
#define IDB_BITMAP_KEY                  113
#define IDD_GEOGRAPHIC_DLG              115
#define IDD_REQUEST_FILE_DLG            116
#define IDD_CONTACT_DLG                 119
#define IDD_PREVIEW_DLG                 120
#define IDD_ERROR_DLG                   121
#define IDD_CERT_LIST_DIALOG            123
#define IDD_ABOUT                       124
#define IDB_BITMAP_STORE_LOCATION       125
#define IDB_BITMAP_STORE_MASK           126
#define IDB_BITMAP_CERTIFICATE_MASK     127
#define IDB_BITMAP_CERTIFICATE          128
#define IDB_BITMAP_STORE                129
#define IDB_BITMAP_STORE_LOCATION_MASK  130
#define IDB_BITMAP_STORE_LOCATION_SEL   131
#define IDB_BITMAP_STORE_LOCATION_SEL_MASK 132
#define IDD_CERT_INSTALL_DIALOG         133
#define IDI_ICON_CERT_LIST_SMALL        136
#define IDI_ICON_CERT_LIST_LARGE        137
#define IDC_TITLE                       1000
#define IDC_INTRO_TEXT                  1001
#define IDC_RADIO1                      1002
#define IDC_RADIO_FILE                  1002
#define IDC_RADIO2                      1003
#define IDC_RADIO_TEXT                  1003
#define IDC_RADIO3                      1004
#define IDC_EDIT2                       1006
#define IDC_ORGANIZATION_UNIT           1006
#define IDC_CITY_LOCALITY               1006
#define IDC_EMAIL                       1006
#define IDC_EDIT_TEXT                   1006
#define IDC_EDIT3                       1007
#define IDC_PHONE_NUMBER                1007
#define IDC_EDIT4                       1008
#define IDC_CHECK1                      1010
#define IDC_OPEN_WITH                   1010
#define IDC_GROUP1                      1011
#define IDC_CERTNAME                    1013
#define IDC_COMBOKEYLENGTH              1014
#define IDC_ORGANIZATION                1015
#define IDC_COMMON_NAME                 1016
#define IDC_COMBO_COUNTRY               1017
#define IDC_EDIT_COUNTRY                1017
#define IDC_STAT_PROVINCE               1018
#define IDC_PREV_KEY_NAME               1019
#define IDC_PREV_KEY_STRENGTH           1020
#define IDC_PREV_COMMON_NAME            1021
#define IDC_PREV_EMAIL                  1022
#define IDC_PREV_ORG                    1023
#define IDC_PREV_ORG_UNIT               1024
#define IDC_PREV_PHONE                  1025
#define IDC_PREV_COUNTRY                1026
#define IDC_PREV_STATE                  1027
#define IDC_PREV_FILE_NAME              1028
#define IDC_ISSUED_TO                   1029
#define IDC__FULL_NAME                  1030
#define IDC_FILE_NAME                   1031
#define IDC_RESULT                      1034
#define IDC_ENCODE_TO_BUFFER            1035
#define IDC_ERRRO_CODE                  1036
#define IDC_EDIT                        1037
#define IDC_SETPATH                     1038
#define IDC_EXIT                        1039
#define IDC_ABOUT                       1040
#define IDC_BROWSE                      1041
#define IDC_STORE_TREE                  1042
#define IDC_CERT_LIST                   1043
#define IDC_STATIC_SPLIT                1044
#define IDC_EDIT_FILE                   1050
#define IDC_BUTTON_BROWSE               1051
#define IDC_STATIC_NOTE                 1053
#define IDC_STATIC                      65535
#define IDC_TEXT_NOTE                   IDC_STATIC_NOTE

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
